In [1]:
!pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 30.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 61.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.2/199.2 KB 6.7 MB/s eta 0:00:00


In [2]:
import pickle as pkl
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from scipy.special import softmax
import numpy as np
import pandas as pd

In [3]:
"""
Mounting G-drive
"""

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
"""
Loading dataset for analysis
"""

df = pd.read_csv(r"/content/drive/MyDrive/Airline_Sentiment_analysis/dataset/Usecase3_Customer_Sentiment_Dataset.csv")

In [5]:
df.head()

airline_sentiment         airline  \
0           neutral  Virgin America   
1          positive  Virgin America   
2           neutral  Virgin America   
3          negative  Virgin America   
4          negative  Virgin America   

                                                text  
0                @VirginAmerica What @dhepburn said.  
1  @VirginAmerica plus you've added commercials t...  
2  @VirginAmerica I didn't today... Must mean I n...  
3  @VirginAmerica it's really aggressive to blast...  
4  @VirginAmerica and it's a really big bad thing...

In [6]:
def tweet_preprocessor(tweet):
    # precprcess tweet
    tweet_words = []

    for word in tweet.split(' '):
        if word.startswith('@') and len(word) > 1:
            word = '@user'
        
        elif word.startswith('http'):
            word = "http"
        tweet_words.append(word)

    tweet_proc = " ".join(tweet_words)
    return tweet_proc

In [30]:
df['text'] = df['text'].apply(lambda x: tweet_preprocessor(x))

In [7]:
# load model and tokenizer
roberta = "cardiffnlp/twitter-roberta-base-sentiment"

model = AutoModelForSequenceClassification.from_pretrained(roberta)
tokenizer = AutoTokenizer.from_pretrained(roberta)

In [8]:
labels = ['negative', 'neutral', 'positive']

In [11]:
def sent_analyze(tweet):
    # sentiment analysis
    tweet = tweet_preprocessor(tweet)
    encoded_tweet = tokenizer(tweet, return_tensors='pt')
    # output = model(encoded_tweet['input_ids'], encoded_tweet['attention_mask'])
    output = model(**encoded_tweet)

    scores = output[0][0].detach().numpy()
    scores = softmax(scores)
    

    a = (np.argmax(scores))
    for i in range(len(scores)):
    
        l = labels[i]
        s = scores[i]
        # print(l,s)
    # print(labels[a])

    return labels[a]

In [12]:
df["RoBERTa_Label"] = df.text.apply(lambda x: sent_analyze(x))

In [13]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_recall_fscore_support

In [14]:
# Compute the confusion matrix
cm = confusion_matrix(df['airline_sentiment'], df['RoBERTa_Label'])
print(cm)

[[6526 2162  490]
 [ 383 2144  572]
 [  38  193 2132]]


In [15]:
precision, recall, f1_score, support = precision_recall_fscore_support(df['airline_sentiment'], df['RoBERTa_Label'], labels=labels)

#Results
print('Precision:', precision)
print('Recall:', recall)
print('F1 score:', f1_score)

Precision: [0.9393983  0.47655034 0.66750157]
Recall: [0.71104816 0.69183608 0.90224291]
F1 score: [0.80942636 0.56435904 0.7673205 ]


In [31]:
# printing and checking the false cases (Labelled vs pretrained output)
for label in labels:
    false_df = df[(df['airline_sentiment'] == label) & (df['RoBERTa_Label'] != label)]

false_df

airline_sentiment         airline  \
1              positive  Virgin America   
40             positive  Virgin America   
114            positive  Virgin America   
148            positive  Virgin America   
183            positive  Virgin America   
...                 ...             ...   
13856          positive        American   
13977          positive        American   
14281          positive        American   
14382          positive        American   
14530          positive        American   

                                                    text RoBERTa_Label  
1      @user plus you've added commercials to the exp...      negative  
40     @user View of downtown Los Angeles, the Hollyw...       neutral  
114    @user come back to #PHL already. We need you t...      negative  
148    @user #flight home to #dc #sunset #globe in' #...       neutral  
183    😎 RT @user You’ve met your match. Got status o...       neutral  
...                                                  ...           ...  
13856        @user #AmericanView Sweet Home Chicago http       neutral  
13977  @user I tried that. They won't book us with an...      negative  
14281  @user Hmm. Looks like you looked at my tweet f...       neutral  
14382  @user I'm flying with your competitor today, s...      negative  
14530  @user thanks for forcing me to check -in my ca...      negative  

[231 rows x 4 columns]

In [20]:
df.shape

(14640, 4)

In [34]:
false_positive = df[(df['airline_sentiment'] == "negative") & (df['RoBERTa_Label'] == "positive")]

false_positive

airline_sentiment         airline  \
55             negative  Virgin America   
82             negative  Virgin America   
106            negative  Virgin America   
217            negative  Virgin America   
288            negative  Virgin America   
...                 ...             ...   
14519          negative        American   
14532          negative        American   
14563          negative        American   
14572          negative        American   
14587          negative        American   

                                                    text RoBERTa_Label  
55     @user hi! i'm so excited about your $99 LGA-&g...      positive  
82     @user you're the best!! Whenever I (begrudging...      positive  
106    @user called your service line and was hung up...      positive  
217    @user I was really looking forward to my fligh...      positive  
288    @user husband and I ordered three drinks via m...      positive  
...                                                  ...           ...  
14519  @user because of you, I am doing the one thing...      positive  
14532      @user missing a full days of work thanks guys      positive  
14563  @user All flts to JFK Cancelled Flightled Thx ...      positive  
14572  @user When I left Orlando, I was 2nd in line f...      positive  
14587  @user I’ll play it by ear. I know that you are...      positive  

[490 rows x 4 columns]

In [33]:
false_negative = df[(df['airline_sentiment'] == "positive") & (df['RoBERTa_Label'] == "negative")]

false_negative

airline_sentiment         airline  \
1              positive  Virgin America   
114            positive  Virgin America   
307            positive  Virgin America   
663            positive          United   
1187           positive          United   
1613           positive          United   
1851           positive          United   
2517           positive          United   
2716           positive          United   
2866           positive          United   
2952           positive          United   
3436           positive          United   
3815           positive          United   
4489           positive       Southwest   
4614           positive       Southwest   
5510           positive       Southwest   
5964           positive       Southwest   
6279           positive       Southwest   
6375           positive       Southwest   
6542           positive       Southwest   
6782           positive           Delta   
6935           positive           Delta   
6968           positive           Delta   
7019           positive           Delta   
7311           positive           Delta   
7662           positive           Delta   
8168           positive           Delta   
8224           positive           Delta   
8298           positive           Delta   
8939           positive           Delta   
11062          positive      US Airways   
11118          positive      US Airways   
11611          positive      US Airways   
11749          positive      US Airways   
11919          positive        American   
13977          positive        American   
14382          positive        American   
14530          positive        American   

                                                    text RoBERTa_Label  
1      @user plus you've added commercials to the exp...      negative  
114    @user come back to #PHL already. We need you t...      negative  
307    @user I mean. Probably inappropriate while on ...      negative  
663    @user private jet would have been cool! Do doe...      negative  
1187   @user The DEN b44 agent (9:30am) was amazing. ...      negative  
1613   @user can Cancelled Flight my flight anytime i...      negative  
1851   @user This is probably the least dependable ai...      negative  
2517   @user thank you.\nIt's my daughters 13th bd pa...      negative  
2716              @user you suck. @user you're the best.      negative  
2866   @user On the plane but thanks! Maybe don't let...      negative  
2952   @user love being told you would issue a refund...      negative  
3436   @user flight attendant regains karma by giving...      negative  
3815   @user Thanks for explanation. It seems like an...      negative  
4489   @user - We left iPad in a seat pocket.  Filed ...      negative  
4614   @user What can we do to bring you back to Jack...      negative  
5510   @user I wish i would've seen this 4 hours ago!...      negative  
5964   @user Again, please accept my apologies for my...      negative  
6279                       @user @user holy fuckinf shit      negative  
6375                 @user hot stewardess flipped me off      negative  
6542   @user thanks for the reply, something is off w...      negative  
6782   @user what are the chances of actually flying ...      negative  
6935   Stop. Please. RT @user Our fleet's on fleek. http      negative  
6968   “@JetBlue: Our fleet's on fleek. http no... Ya...      negative  
7019   Don't show these to Larry Fedora. RT @user Our...      negative  
7311   @user @user please give JetBlue all the permis...      negative  
7662   @user thank you! I know the weather in #Boston...      negative  
8168   @user you don't remember our date Monday night...      negative  
8224   @user yes thankfully! Catering just got here a...      negative  
8298   .@JetBlue Wish you would make Austin, TX a hub...      negative  
8939   @user well lucky I only fly JB..I guess I woul...      negative  
11062  @user I miss you too. Work has taken me out of...      neg

In [28]:
false_positive.shape

(490, 4)

In [29]:
false_negative.shape

(38, 4)

In [35]:
# Looks like, most of false negatives are actually negatives. Also, false positive contains sarcasm. sometimes appreciation and depriciation in one tweet, which is dicy for LM.